//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace PSP.TSSServer {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TSSUserServiceSoapBinding", Namespace="http://172.21.185.177:8080/axis/services/TSSUserService")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ProbeDTO))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ReadingStationDTO))]
    public partial class UserFacadeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLastHourOfReadingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHistoricalDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReadingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewestReadingsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserFacadeService() {
            this.Url = global::PSP.Properties.Settings.Default.PSP_TSSServer_UserFacadeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event getLastHourOfReadingsCompletedEventHandler getLastHourOfReadingsCompleted;
        
        /// <remarks/>
        public event getHistoricalDataCompletedEventHandler getHistoricalDataCompleted;
        
        /// <remarks/>
        public event getReadingsCompletedEventHandler getReadingsCompleted;
        
        /// <remarks/>
        public event getNewestReadingsCompletedEventHandler getNewestReadingsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://172.21.185.177:8080/axis/services/TSSUserService")]
        [return: System.Xml.Serialization.SoapElementAttribute("loginReturn")]
        public bool login(UserDTO in0) {
            object[] results = this.Invoke("login", new object[] {
                        in0});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(UserDTO in0) {
            this.loginAsync(in0, null);
        }
        
        /// <remarks/>
        public void loginAsync(UserDTO in0, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        in0}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://172.21.185.177:8080/axis/services/TSSUserService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getLastHourOfReadingsReturn")]
        public ReadingStationDTO[] getLastHourOfReadings() {
            object[] results = this.Invoke("getLastHourOfReadings", new object[0]);
            return ((ReadingStationDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void getLastHourOfReadingsAsync() {
            this.getLastHourOfReadingsAsync(null);
        }
        
        /// <remarks/>
        public void getLastHourOfReadingsAsync(object userState) {
            if ((this.getLastHourOfReadingsOperationCompleted == null)) {
                this.getLastHourOfReadingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLastHourOfReadingsOperationCompleted);
            }
            this.InvokeAsync("getLastHourOfReadings", new object[0], this.getLastHourOfReadingsOperationCompleted, userState);
        }
        
        private void OngetLastHourOfReadingsOperationCompleted(object arg) {
            if ((this.getLastHourOfReadingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLastHourOfReadingsCompleted(this, new getLastHourOfReadingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://172.21.185.177:8080/axis/services/TSSUserService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getHistoricalDataReturn")]
        public SummaryDTO getHistoricalData(System.DateTime in0, System.DateTime in1) {
            object[] results = this.Invoke("getHistoricalData", new object[] {
                        in0,
                        in1});
            return ((SummaryDTO)(results[0]));
        }
        
        /// <remarks/>
        public void getHistoricalDataAsync(System.DateTime in0, System.DateTime in1) {
            this.getHistoricalDataAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getHistoricalDataAsync(System.DateTime in0, System.DateTime in1, object userState) {
            if ((this.getHistoricalDataOperationCompleted == null)) {
                this.getHistoricalDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHistoricalDataOperationCompleted);
            }
            this.InvokeAsync("getHistoricalData", new object[] {
                        in0,
                        in1}, this.getHistoricalDataOperationCompleted, userState);
        }
        
        private void OngetHistoricalDataOperationCompleted(object arg) {
            if ((this.getHistoricalDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHistoricalDataCompleted(this, new getHistoricalDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://172.21.185.177:8080/axis/services/TSSUserService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getReadingsReturn")]
        public ReadingStationDTO[] getReadings(System.DateTime in0, System.DateTime in1) {
            object[] results = this.Invoke("getReadings", new object[] {
                        in0,
                        in1});
            return ((ReadingStationDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void getReadingsAsync(System.DateTime in0, System.DateTime in1) {
            this.getReadingsAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getReadingsAsync(System.DateTime in0, System.DateTime in1, object userState) {
            if ((this.getReadingsOperationCompleted == null)) {
                this.getReadingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReadingsOperationCompleted);
            }
            this.InvokeAsync("getReadings", new object[] {
                        in0,
                        in1}, this.getReadingsOperationCompleted, userState);
        }
        
        private void OngetReadingsOperationCompleted(object arg) {
            if ((this.getReadingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReadingsCompleted(this, new getReadingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://172.21.185.177:8080/axis/services/TSSUserService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getNewestReadingsReturn")]
        public ReadingStationDTO[] getNewestReadings() {
            object[] results = this.Invoke("getNewestReadings", new object[0]);
            return ((ReadingStationDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void getNewestReadingsAsync() {
            this.getNewestReadingsAsync(null);
        }
        
        /// <remarks/>
        public void getNewestReadingsAsync(object userState) {
            if ((this.getNewestReadingsOperationCompleted == null)) {
                this.getNewestReadingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewestReadingsOperationCompleted);
            }
            this.InvokeAsync("getNewestReadings", new object[0], this.getNewestReadingsOperationCompleted, userState);
        }
        
        private void OngetNewestReadingsOperationCompleted(object arg) {
            if ((this.getNewestReadingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewestReadingsCompleted(this, new getNewestReadingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class UserDTO {
        
        private int accountTypeIdField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        public int accountTypeId {
            get {
                return this.accountTypeIdField;
            }
            set {
                this.accountTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://server.group1.onk.iha.dk")]
    public partial class SummaryDTO {
        
        private string[] alarmsField;
        
        private double periodHighestPressureField;
        
        private double periodHighestTempField;
        
        private double periodLowestPressureField;
        
        private double periodLowestTempField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] alarms {
            get {
                return this.alarmsField;
            }
            set {
                this.alarmsField = value;
            }
        }
        
        /// <remarks/>
        public double periodHighestPressure {
            get {
                return this.periodHighestPressureField;
            }
            set {
                this.periodHighestPressureField = value;
            }
        }
        
        /// <remarks/>
        public double periodHighestTemp {
            get {
                return this.periodHighestTempField;
            }
            set {
                this.periodHighestTempField = value;
            }
        }
        
        /// <remarks/>
        public double periodLowestPressure {
            get {
                return this.periodLowestPressureField;
            }
            set {
                this.periodLowestPressureField = value;
            }
        }
        
        /// <remarks/>
        public double periodLowestTemp {
            get {
                return this.periodLowestTempField;
            }
            set {
                this.periodLowestTempField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class ProbeDTO {
        
        private double dataField;
        
        private int idField;
        
        private double lowerAlarmField;
        
        private string unitsField;
        
        private double upperAlarmField;
        
        /// <remarks/>
        public double data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public double lowerAlarm {
            get {
                return this.lowerAlarmField;
            }
            set {
                this.lowerAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        public double upperAlarm {
            get {
                return this.upperAlarmField;
            }
            set {
                this.upperAlarmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class ReadingStationDTO {
        
        private bool enabledField;
        
        private string nameField;
        
        private ProbeDTO[] probesField;
        
        /// <remarks/>
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ProbeDTO[] probes {
            get {
                return this.probesField;
            }
            set {
                this.probesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getLastHourOfReadingsCompletedEventHandler(object sender, getLastHourOfReadingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLastHourOfReadingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLastHourOfReadingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReadingStationDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReadingStationDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getHistoricalDataCompletedEventHandler(object sender, getHistoricalDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHistoricalDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHistoricalDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SummaryDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SummaryDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getReadingsCompletedEventHandler(object sender, getReadingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReadingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReadingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReadingStationDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReadingStationDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getNewestReadingsCompletedEventHandler(object sender, getNewestReadingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewestReadingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewestReadingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReadingStationDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReadingStationDTO[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591