//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="TSSAdminServiceSoapBinding", Namespace="http://localhost:8080/axis/services/TSSAdminService")]
public partial class AdminFacadeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback removeUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback setRSNameOperationCompleted;
    
    private System.Threading.SendOrPostCallback addUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback addUser1OperationCompleted;
    
    private System.Threading.SendOrPostCallback addAdminOperationCompleted;
    
    private System.Threading.SendOrPostCallback addAdmin1OperationCompleted;
    
    private System.Threading.SendOrPostCallback updateUserInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback setRSAlarmLevelOperationCompleted;
    
    private System.Threading.SendOrPostCallback enableRSOperationCompleted;
    
    private System.Threading.SendOrPostCallback disableRSOperationCompleted;
    
    /// <remarks/>
    public AdminFacadeService() {
        this.Url = "http://172.21.185.177:8080/axis/services/TSSAdminService";
    }
    
    /// <remarks/>
    public event removeUserCompletedEventHandler removeUserCompleted;
    
    /// <remarks/>
    public event setRSNameCompletedEventHandler setRSNameCompleted;
    
    /// <remarks/>
    public event addUserCompletedEventHandler addUserCompleted;
    
    /// <remarks/>
    public event addUser1CompletedEventHandler addUser1Completed;
    
    /// <remarks/>
    public event addAdminCompletedEventHandler addAdminCompleted;
    
    /// <remarks/>
    public event addAdmin1CompletedEventHandler addAdmin1Completed;
    
    /// <remarks/>
    public event updateUserInfoCompletedEventHandler updateUserInfoCompleted;
    
    /// <remarks/>
    public event setRSAlarmLevelCompletedEventHandler setRSAlarmLevelCompleted;
    
    /// <remarks/>
    public event enableRSCompletedEventHandler enableRSCompleted;
    
    /// <remarks/>
    public event disableRSCompletedEventHandler disableRSCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("removeUserReturn")]
    public bool removeUser(string in0) {
        object[] results = this.Invoke("removeUser", new object[] {
                    in0});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginremoveUser(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("removeUser", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndremoveUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void removeUserAsync(string in0) {
        this.removeUserAsync(in0, null);
    }
    
    /// <remarks/>
    public void removeUserAsync(string in0, object userState) {
        if ((this.removeUserOperationCompleted == null)) {
            this.removeUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveUserOperationCompleted);
        }
        this.InvokeAsync("removeUser", new object[] {
                    in0}, this.removeUserOperationCompleted, userState);
    }
    
    private void OnremoveUserOperationCompleted(object arg) {
        if ((this.removeUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.removeUserCompleted(this, new removeUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("setRSNameReturn")]
    public bool setRSName(string in0, string in1) {
        object[] results = this.Invoke("setRSName", new object[] {
                    in0,
                    in1});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsetRSName(string in0, string in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("setRSName", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndsetRSName(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void setRSNameAsync(string in0, string in1) {
        this.setRSNameAsync(in0, in1, null);
    }
    
    /// <remarks/>
    public void setRSNameAsync(string in0, string in1, object userState) {
        if ((this.setRSNameOperationCompleted == null)) {
            this.setRSNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRSNameOperationCompleted);
        }
        this.InvokeAsync("setRSName", new object[] {
                    in0,
                    in1}, this.setRSNameOperationCompleted, userState);
    }
    
    private void OnsetRSNameOperationCompleted(object arg) {
        if ((this.setRSNameCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.setRSNameCompleted(this, new setRSNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("addUserReturn")]
    public bool addUser(MeasurementDTO in0) {
        object[] results = this.Invoke("addUser", new object[] {
                    in0});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddUser(MeasurementDTO in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addUser", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndaddUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void addUserAsync(MeasurementDTO in0) {
        this.addUserAsync(in0, null);
    }
    
    /// <remarks/>
    public void addUserAsync(MeasurementDTO in0, object userState) {
        if ((this.addUserOperationCompleted == null)) {
            this.addUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddUserOperationCompleted);
        }
        this.InvokeAsync("addUser", new object[] {
                    in0}, this.addUserOperationCompleted, userState);
    }
    
    private void OnaddUserOperationCompleted(object arg) {
        if ((this.addUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.addUserCompleted(this, new addUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute(MessageName="addUser1")]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("addUserReturn")]
    public bool addUser(string in0, string in1) {
        object[] results = this.Invoke("addUser1", new object[] {
                    in0,
                    in1});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddUser1(string in0, string in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addUser1", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndaddUser1(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void addUser1Async(string in0, string in1) {
        this.addUser1Async(in0, in1, null);
    }
    
    /// <remarks/>
    public void addUser1Async(string in0, string in1, object userState) {
        if ((this.addUser1OperationCompleted == null)) {
            this.addUser1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddUser1OperationCompleted);
        }
        this.InvokeAsync("addUser1", new object[] {
                    in0,
                    in1}, this.addUser1OperationCompleted, userState);
    }
    
    private void OnaddUser1OperationCompleted(object arg) {
        if ((this.addUser1Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.addUser1Completed(this, new addUser1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("addAdminReturn")]
    public bool addAdmin(MeasurementDTO in0) {
        object[] results = this.Invoke("addAdmin", new object[] {
                    in0});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddAdmin(MeasurementDTO in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addAdmin", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndaddAdmin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void addAdminAsync(MeasurementDTO in0) {
        this.addAdminAsync(in0, null);
    }
    
    /// <remarks/>
    public void addAdminAsync(MeasurementDTO in0, object userState) {
        if ((this.addAdminOperationCompleted == null)) {
            this.addAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAdminOperationCompleted);
        }
        this.InvokeAsync("addAdmin", new object[] {
                    in0}, this.addAdminOperationCompleted, userState);
    }
    
    private void OnaddAdminOperationCompleted(object arg) {
        if ((this.addAdminCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.addAdminCompleted(this, new addAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute(MessageName="addAdmin1")]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("addAdminReturn")]
    public bool addAdmin(string in0, string in1) {
        object[] results = this.Invoke("addAdmin1", new object[] {
                    in0,
                    in1});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddAdmin1(string in0, string in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addAdmin1", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndaddAdmin1(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void addAdmin1Async(string in0, string in1) {
        this.addAdmin1Async(in0, in1, null);
    }
    
    /// <remarks/>
    public void addAdmin1Async(string in0, string in1, object userState) {
        if ((this.addAdmin1OperationCompleted == null)) {
            this.addAdmin1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAdmin1OperationCompleted);
        }
        this.InvokeAsync("addAdmin1", new object[] {
                    in0,
                    in1}, this.addAdmin1OperationCompleted, userState);
    }
    
    private void OnaddAdmin1OperationCompleted(object arg) {
        if ((this.addAdmin1Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.addAdmin1Completed(this, new addAdmin1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("updateUserInfoReturn")]
    public bool updateUserInfo(MeasurementDTO in0, MeasurementDTO in1) {
        object[] results = this.Invoke("updateUserInfo", new object[] {
                    in0,
                    in1});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginupdateUserInfo(MeasurementDTO in0, MeasurementDTO in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("updateUserInfo", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndupdateUserInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void updateUserInfoAsync(MeasurementDTO in0, MeasurementDTO in1) {
        this.updateUserInfoAsync(in0, in1, null);
    }
    
    /// <remarks/>
    public void updateUserInfoAsync(MeasurementDTO in0, MeasurementDTO in1, object userState) {
        if ((this.updateUserInfoOperationCompleted == null)) {
            this.updateUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateUserInfoOperationCompleted);
        }
        this.InvokeAsync("updateUserInfo", new object[] {
                    in0,
                    in1}, this.updateUserInfoOperationCompleted, userState);
    }
    
    private void OnupdateUserInfoOperationCompleted(object arg) {
        if ((this.updateUserInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.updateUserInfoCompleted(this, new updateUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("setRSAlarmLevelReturn")]
    public bool setRSAlarmLevel(string in0, int in1) {
        object[] results = this.Invoke("setRSAlarmLevel", new object[] {
                    in0,
                    in1});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsetRSAlarmLevel(string in0, int in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("setRSAlarmLevel", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndsetRSAlarmLevel(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void setRSAlarmLevelAsync(string in0, int in1) {
        this.setRSAlarmLevelAsync(in0, in1, null);
    }
    
    /// <remarks/>
    public void setRSAlarmLevelAsync(string in0, int in1, object userState) {
        if ((this.setRSAlarmLevelOperationCompleted == null)) {
            this.setRSAlarmLevelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRSAlarmLevelOperationCompleted);
        }
        this.InvokeAsync("setRSAlarmLevel", new object[] {
                    in0,
                    in1}, this.setRSAlarmLevelOperationCompleted, userState);
    }
    
    private void OnsetRSAlarmLevelOperationCompleted(object arg) {
        if ((this.setRSAlarmLevelCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.setRSAlarmLevelCompleted(this, new setRSAlarmLevelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("enableRSReturn")]
    public bool enableRS(string in0) {
        object[] results = this.Invoke("enableRS", new object[] {
                    in0});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginenableRS(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("enableRS", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndenableRS(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void enableRSAsync(string in0) {
        this.enableRSAsync(in0, null);
    }
    
    /// <remarks/>
    public void enableRSAsync(string in0, object userState) {
        if ((this.enableRSOperationCompleted == null)) {
            this.enableRSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenableRSOperationCompleted);
        }
        this.InvokeAsync("enableRS", new object[] {
                    in0}, this.enableRSOperationCompleted, userState);
    }
    
    private void OnenableRSOperationCompleted(object arg) {
        if ((this.enableRSCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.enableRSCompleted(this, new enableRSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server.group1.onk.iha.dk", ResponseNamespace="http://localhost:8080/axis/services/TSSAdminService")]
    [return: System.Xml.Serialization.SoapElementAttribute("disableRSReturn")]
    public bool disableRS(string in0) {
        object[] results = this.Invoke("disableRS", new object[] {
                    in0});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindisableRS(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("disableRS", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EnddisableRS(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void disableRSAsync(string in0) {
        this.disableRSAsync(in0, null);
    }
    
    /// <remarks/>
    public void disableRSAsync(string in0, object userState) {
        if ((this.disableRSOperationCompleted == null)) {
            this.disableRSOperationCompleted = new System.Threading.SendOrPostCallback(this.OndisableRSOperationCompleted);
        }
        this.InvokeAsync("disableRS", new object[] {
                    in0}, this.disableRSOperationCompleted, userState);
    }
    
    private void OndisableRSOperationCompleted(object arg) {
        if ((this.disableRSCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.disableRSCompleted(this, new disableRSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
public partial class MeasurementDTO {
    
    private string passwordField;
    
    private string usernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void removeUserCompletedEventHandler(object sender, removeUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class removeUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal removeUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void setRSNameCompletedEventHandler(object sender, setRSNameCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class setRSNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal setRSNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void addUserCompletedEventHandler(object sender, addUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class addUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal addUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void addUser1CompletedEventHandler(object sender, addUser1CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class addUser1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal addUser1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void addAdminCompletedEventHandler(object sender, addAdminCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class addAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal addAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void addAdmin1CompletedEventHandler(object sender, addAdmin1CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class addAdmin1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal addAdmin1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void updateUserInfoCompletedEventHandler(object sender, updateUserInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class updateUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal updateUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void setRSAlarmLevelCompletedEventHandler(object sender, setRSAlarmLevelCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class setRSAlarmLevelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal setRSAlarmLevelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void enableRSCompletedEventHandler(object sender, enableRSCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class enableRSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal enableRSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void disableRSCompletedEventHandler(object sender, disableRSCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class disableRSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal disableRSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}
